[project]
name = "twitter-django-nextjs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asgiref==3.8.1",
    "celery>=5.6.3",
    "django==5.0.6",
    "django-redis>=6.0.0",
    "djangorestframework==3.15.1",
    "djangorestframework-simplejwt==5.3.1",
    "drf-nested-routers==0.94.1",
    "pillow>=10.3.0",
    "pyjwt==2.8.0",
    "python-dotenv==1.0.1",
    "redis>=8.1.0",
    "sqlparse==0.5.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0",
]
