# Generated by Django 5.0.6 on 2024-05-20 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
        ('tweets', '0003_remove_reply_post_image_reply_reply_tweet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='tweets',
            field=models.ManyToManyField(blank=True, related_name='tweets_set', to='tweets.tweet'),
        ),
        migrations.AlterField(
            model_name='list',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
