# Generated by Django 5.0.6 on 2024-05-25 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_alter_list_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tweets',
        ),
        migrations.RemoveField(
            model_name='list',
            name='users',
        ),
        migrations.AddField(
            model_name='list',
            name='followed_users',
            field=models.ManyToManyField(blank=True, related_name='followed_users_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='following_users',
            field=models.ManyToManyField(blank=True, related_name='following_users_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
