# Generated by Django 5.0.6 on 2024-05-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_listtweetmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListTweetModel',
        ),
    ]
